name: C/C++ CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make setup all

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: tests
      run: make setup test
